[package]
name = "advent_of_code_2021_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
ndarray-stats = "0.5.0"
noisy_float = "0.2.0"
petgraph = "0.6.0"
rayon = "1.5"